config/routes.rb
Rails.application.routes.draw do
  resources :maintenances
  resources :motors
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'homes/index'
  get 'homes/terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
  belongs_to :user
  belongs_to :motor, dependent: :destroy
  belongs_to :city
  belongs_to :material, class_name: 'Material', foreign_key: 'material_id', dependent: :destroy
  belongs_to :type_of_maintenance

  validates :email, presence: true
  validates :date_job, presence: true
end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  before_action :set_maintenance, only: %i[ show edit update destroy ]

  before_action :authenticate_user!

  # GET /maintenances or /maintenances.json
  def index
    @maintenances = Maintenance.all
    @pagy, @maintenances = pagy(Maintenance.all)
  end

  # GET /maintenances/1 or /maintenances/1.json
  def show
  end

  # GET /maintenances/new
  def new
    @maintenance = Maintenance.new
  end

  # GET /maintenances/1/edit
  def edit
  end

  # POST /maintenances or /maintenances.json
  def create
    @maintenance = Maintenance.new(maintenance_params)

    respond_to do |format|
      if @maintenance.save
        format.html { redirect_to maintenance_url(@maintenance), notice: "Maintenance was successfully created." }
        format.json { render :show, status: :created, location: @maintenance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenances/1 or /maintenances/1.json
  def update
    respond_to do |format|
      if @maintenance.update(maintenance_params)
        format.html { redirect_to maintenance_url(@maintenance), notice: "Maintenance was successfully updated." }
        format.json { render :show, status: :ok, location: @maintenance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenances/1 or /maintenances/1.json
  def destroy
    @maintenance.destroy

    respond_to do |format|
      format.html { redirect_to maintenances_url, notice: "Maintenance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance
      @maintenance = Maintenance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_params
      params.require(:maintenance).permit(:email, :date_job, :user_id, :motor_id, :city_id, :material_id, :type_of_maintenance_id)
    end
end

app/helpers/maintenances_helper.rb
module MaintenancesHelper
end

app/views/maintenances/_form.html.erb
<%= form_with(model: maintenance) do |form| %>
  <% if maintenance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(maintenance.errors.count, "error") %> prohibited this maintenance from being saved:</h2>

      <ul>
        <% maintenance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :date_job, style: "display: block" %>
    <%= form.date_field :date_job %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :motor_id, style: "display: block" %>
    <%= form.text_field :motor_id %>
  </div>

  <div>
    <%= form.label :city_id, style: "display: block" %>
    <%= form.select :city_id, City.all.collect {|c| [c.name, c.id]} %>
  </div>

  <div>
    <%= form.label :material_id, style: "display: block" %>
    <%= form.select :material_id, Material.all.collect {|c| [c.name, c.id]} %>
  </div>

  <div>
    <%= form.label :type_of_maintenance_id, style: "display: block" %>
    <%= form.select :type_of_maintenance_id, TypeOfMaintenance.all.collect {|c| [c.name, c.id]} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/maintenances/_maintenance.html.erb
<div id="<%= dom_id maintenance %>">
  <p>
    <strong>Email:</strong>
    <%= maintenance.email %>
  </p>

  <p>
    <strong>Date job:</strong>
    <%= maintenance.date_job %>
  </p>

  <p>
    <strong>User:</strong>
    <%= maintenance.user_id %>
  </p>

  <p>
    <strong>Motor:</strong>
    <%= maintenance.motor_id %>
  </p>

  <p>
    <strong>City:</strong>
    <%= maintenance.city_id %>
  </p>

  <p>
    <strong>Materials:</strong>
    <%= maintenance.material_id %>
  </p>

  <p>
    <strong>Type of maintenance:</strong>
    <%= maintenance.type_of_maintenance_id %>
  </p>

</div>

app/views/maintenances/edit.html.erb
<h1>Editing maintenance</h1>

<%= render "form", maintenance: @maintenance %>

<br>

<div>
  <%= link_to "Show this maintenance", @maintenance %> |
  <%= link_to "Back to maintenances", maintenances_path %>
</div>

app/views/maintenances/index.html.erb
<h1 class="text-center">MANTENIMIENTOS DE MOTORES</h1>
<br>
<div class="container">
    <table class="table table-dark table-hover">
      <thead>
        <tr>
          <th>Tipo de motor</th>
          <th>Tipo de Mantenimiento</th>
          <th>Nombre del motor</th>
          <th>Ciudad</th>
          <th>Materiales utilizados</th>
          <th>Fecha de realización</th>
          <th>Email técnico</th>
          <th>Fecha del mantenimiento</th>
        </tr>
      </thead>
      <% @maintenances.each do |maintenance| %>
      <tbody>
        <tr>
          <td><%= maintenance.motor_id %></td>
          <td><%= maintenance.type_of_maintenance_id %></td>
          <td><%= maintenance.motor_id %></td>
          <td><%= maintenance.city_id %></td>
          <td><%= maintenance.material_id %></td>
          <td><%= maintenance.created_at %></td>
          <td><%= maintenance.email %></td>
          <td><%= maintenance.date_job %></td>
        </tr>
      </tbody>
      <% end %>
    </table>  
</div>

<div class="pag-bar mt-3 pt-3">
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

<%= link_to "Ingresa un nuevo mantenimiento", new_maintenance_path, class: 'btn btn-primary', id: 'btn-custom' %>
<br>
<br>

<%# <div id="maintenances"> %>
  <%# <% @maintenances.each do |maintenance| %> 
    <%# <%= render maintenance %> 
    <%# <p> %>
      <%# <%= link_to "Show this maintenance" %> 
    <%# </p> %>
  <%# <% end %> 
<%# </div> %>

app/views/maintenances/new.html.erb
<h1>Nuevo mantenimiento</h1>

<%= render "form", maintenance: @maintenance %>

<br>

<div>
  <%= link_to "Back to maintenances", maintenances_path %>
</div>

app/views/maintenances/show.html.erb
<%= render @maintenance %>

<div>
  <%= link_to "Edit this maintenance", edit_maintenance_path(@maintenance) %> |
  <%= link_to "Back to maintenances", maintenances_path %>

  <%= button_to "Destroy this maintenance", @maintenance, method: :delete %>
</div>