config/routes.rb
Rails.application.routes.draw do
  resources :maintenances
  resources :motors
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'homes/index'
  get 'homes/terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/motor.rb
class Motor < ApplicationRecord
  belongs_to :type_of_equipment
  has_one_attached :image
  has_many :maintenances, dependent: :destroy

  validates :name, presence: true
  validates :type_of_equipment_id, presence: true
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  before_action :set_motor, only: %i[ show edit update destroy ]

  before_action :authenticate_user!

  # GET /motors or /motors.json
  def index
    @motors = Motor.all
    @pagy, @motors = pagy(Motor.all)
    @can_create_motor = current_user.role == 'operador'
  end

  # GET /motors/1 or /motors/1.json
  def show
  end

  # GET /motors/new
  def new
    @motor = Motor.new
  end

  # GET /motors/1/edit
  def edit
  end

  # POST /motors or /motors.json
  def create
    @motor = Motor.new(motor_params)
    @motor.image.attach(params[:motor][:image]) if params[:motor][:image]

    respond_to do |format|
      if @motor.save
        format.html { redirect_to motor_url(@motor), notice: "Motor was successfully created." }
        format.json { render :show, status: :created, location: @motor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motors/1 or /motors/1.json
  def update
    respond_to do |format|
      if @motor.update(motor_params)
        format.html { redirect_to motor_url(@motor), notice: "Motor was successfully updated." }
        format.json { render :show, status: :ok, location: @motor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motors/1 or /motors/1.json
  def destroy
    @motor.destroy

    respond_to do |format|
      format.html { redirect_to motors_url, notice: "Motor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motor
      @motor = Motor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def motor_params
      params.require(:motor).permit(:name, :description, :image, :type_of_equipment_id)
    end
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/views/motors/_form.html.erb
<%= form_with(model: motor) do |form| %>
  <% if motor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(motor.errors.count, "error") %> prohibited this motor from being saved:</h2>

      <ul>
        <% motor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :type_of_equipment_id, style: "display: block" %>
    <%= form.select :type_of_equipment_id, TypeOfEquipment.all.collect {|c| [c.name, c.id]} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/motors/_motor.html.erb
<div id="<%= dom_id motor %>">
  <p>
    <strong>Name:</strong>
    <%= motor.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= motor.description %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= link_to motor.image.filename, motor.image if motor.image.attached? %>
  </p>

  <p>
    <strong>Type of equipment:</strong>
    <%= motor.type_of_equipment_id %>
  </p>

</div>

app/views/motors/edit.html.erb
<h1>Editing motor</h1>

<%= render "form", motor: @motor %>

<br>

<div>
  <%= link_to "Show this motor", @motor %> |
  <%= link_to "Back to motors", motors_path %>
</div>

app/views/motors/index.html.erb
<h1 class="text-center">MOTORES</h1>
<br>
<div class="container">
  <table class="table table-dark table-hover">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Tipo de equipo</th>
        <th>Imagen del motor</th>
        <th>Ver motor</th>
      </tr>
    </thead>
    <tbody>
      <% @motors.each do |motor| %>
        <tr>
          <td><%= motor.name %></td>
          <td><%= motor.description %></td>
          <td><%= motor.type_of_equipment_id %></td>
          <td><%= link_to motor.image.filename, motor.image if motor.image.attached? %></td>
          <td>
            <%= link_to motor do %>
              <i class="fa-solid fa-eye custom-icon"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="pag-bar mt-3 pt-3">
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

<%= link_to 'Ingresa un nuevo motor', new_motor_path, class: 'btn btn-primary', id: 'btn-custom' %>
<br>
<br>
<br>

app/views/motors/new.html.erb
<h1>Nuevo motor</h1>

<%= render "form", motor: @motor %>

<br>

<div>
  <%= link_to "Back to motors", motors_path %>
</div>

app/views/motors/show.html.erb
<%= image_tag @motor.image if @motor.image.attached? %>
<%= render @motor %>

<div>
  <%= link_to "Edit this motor", edit_motor_path(@motor) %> |
  <%= link_to "Back to motors", motors_path %>

  <%= button_to "Destroy this motor", @motor, method: :delete %>
</div>