config/routes.rb
Rails.application.routes.draw do
  resources :maintenances
  resources :motors
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'homes/index'
  get 'homes/terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JetmaintainDanielanahuelpan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary"> 
      <div class="container">
          <%= link_to root_path, class: 'navbar-brand' do %>
              <%= image_tag 'motor.png', alt: 'Motor', width: '70px' %>
          <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to current_user.email, homes_index_path, class: "nav-link text-white" %>
              </li>
              <li class="nav-item text_white">
                <%= link_to "Cerrar sesión", destroy_user_session_path, class: "nav-link text-white" %>
              </li>
              <li class="nav-item">
                <%= link_to "Motores", motors_path, class: "nav-link text-white" %>  
              </li>
              <li class="nav-item">
                <%# <%= link_to "Términos y condiciones", homes_terms_path, class: "nav-link text-white" %> 
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
              </li>
            <% end %>
              <li class="nav-item">
                <%= link_to "Inicio", homes_index_path, class: "nav-link text-white" %> 
              </li>
              <li class="nav-item">
                <%= link_to "Mantenimientos de motores", maintenances_path, class: "nav-link text-white" %>
              </li>
              <li class="nav-item">
                <%= link_to "Términos y condiciones", homes_terms_path, class: "nav-link text-white" %>
              </li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>